swagger: '2.0'
info:
  description: Catering falcon Portal services
  version: 0.0.1
  title: catering falcon Portal  services
  contact:
    name: API Support
    email: mohammad.umaruddin@dnata.com
host: '52.188.192.123:9002'
basePath: /cfp/services/recipe-engine-service
schemes:
  - http
paths:
  /enginerecipe/:
    x-swagger-router-controller: recipeEngineService
    post:
      tags:
        - enginerecipe process
      summary: create and process enginerecipe for airlines.
      description: Airline can place enginerecipe for catering
      operationId: processRecipeEngine
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/enginerecipeDetails'
      responses:
        '200':
          description: enginerecipe details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new enginerecipe
        default:
          description: Unexpected error
    get:
      tags:
        - enginerecipe process
      summary: get enginerecipe details.
      description: can get enginerecipe details
      operationId: getEnginerecipes
      produces:
        - application/json
      responses:
        '200':
          description: enginerecipe details
          schema:
            type: object
            properties: {}
        '400':
          description: Error getting enginerecipe Info
        default:
          description: Unexpected error
  /enginerecipe/all:
    x-swagger-router-controller: recipeEngineService
    post:
      tags:
        - enginerecipe process
      summary: create and process enginerecipe for airlines.
      description: Airline can place enginerecipe for catering
      operationId: processAllRecipeEngine
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/enginerecipeDetails'
      responses:
        '200':
          description: enginerecipe details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new enginerecipe
        default:
          description: Unexpected error
  '/enginerecipe/{recipe_id}/order/{order_processing_id}':
    x-swagger-router-controller: recipeEngineService
    put:
      tags:
        - enginerecipe process
      summary: update a enginerecipe.
      description: Airline can update enginerecipe if it not processed
      operationId: updateEnginerecipeWithEnginerecipeId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: recipe_id
          in: path
          type: string
          required: true
        - name: order_processing_id
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/enginerecipeSearch'
      responses:
        '200':
          description: lists details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new publishers
        default:
          description: Unexpected error
    get:
      tags:
        - enginerecipe process
      summary: get enginerecipe all enginerecipes list.
      description: can get all enginerecipe list
      operationId: getEnginerecipeWithEnginerecipeId
      produces:
        - application/json
      parameters:
        - name: recipe_id
          in: path
          type: string
          required: true
        - name: order_processing_id
          in: path
          type: string
          required: true
      responses:
        '200':
          description: enginerecipe list
          schema:
            type: object
            properties: {}
        '400':
          description: Error getting enginerecipe Info
        default:
          description: Unexpected error
  /swagger: 
    x-swagger-pipe: swagger_raw
definitions:
  enginerecipeDetails:
    type: object
  enginerecipeSearch:
    type: object
  