swagger: '2.0'
info:
  description: Catering falcon Portal services
  version: 0.0.1
  title: catering falcon Portal  services
  contact:
    name: API Support
    email: mohammad.umaruddin@dnata.com
basePath: /cfp/services/order-processing-service
schemes:
  - http
paths:
  /order/process/carrier/{carrierCode}:
    x-swagger-router-controller: orderProcessingService
    post:
      tags:
        - order process
      summary: create and process order for airlines.
      description: Airline can place order for catering
      operationId: createOrderForAirline
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: carrierCode
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/orderDetails'
      responses:
        '200':
          description: order details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new order
        default:
          description: Unexpected error
    get:
      tags:
        - order process
      summary: get order details.
      description:  can get order details
      operationId: getOrdersForAirline
      produces:
        - application/json
      parameters:
        - name: carrierCode
          in: path
          type: string
          required: true
      responses:
        '200':
          description: order details
          schema:
            type: object
            properties: {}
        '400':
          description: Error getting order Info
        default:
          description: Unexpected error      
          
  
  /order/process/{order_processing_id}:
    x-swagger-router-controller: orderProcessingService
    put:
      tags:
        - order process
      summary: update a order.
      description: Airline can update order if it not processed
      operationId: updateOrderWithOrderProcessId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: order_processing_id
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/updateOrderDetails'
      responses:
        '200':
          description: lists details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new publishers
        default:
          description: Unexpected error
    get:
      tags:
        - order process
      summary: get order all orders list.
      description:  can get all order list
      operationId: getOrderWithOrderProcessId
      produces:
        - application/json
      parameters:
        - name: order_processing_id
          in: path
          type: string
          required: true
      responses:
        '200':
          description: order list
          schema:
            type: object
            properties: {}
        '400':
          description: Error getting order Info
        default:
          description: Unexpected error
  /order/process/origin/{boardingPoint}/status/{status}:
    x-swagger-router-controller: orderProcessingService
    get:
      tags:
        - order process details for masterchef
      summary: get order details with status processed or pending or not processed or rejected
      description: create and process order for all airlines 
      operationId: getAllOrdersWithStatus
      produces:
        - application/json
      parameters:
        - name: status
          in: path
          type: string
          required: true
        - name: boardingPoint
          in: path
          type: string
          required: true
      responses:
        '200':
          description: order details
          schema:
            type: object
            properties: {}
        '400':
          description: Error creating a new order
        default:
          description: Unexpected error
    

  /swagger: 
    x-swagger-pipe: swagger_raw
definitions:
  order:
    type: object
    required:
      - orderDetails
    properties:
      orderDetails:
        $ref: '#/definitions/orderDetails'
  orderDetails:
    type: object
  updateOrderDetails:
    type: object
